name: Build Web Theme Koala

on:
  push:
    paths:
      - packages/modules/web_themes/koala/source/**
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: packages/modules/web_themes/koala/source/package-lock.json

      - name: Install Dependencies and Build
        run: |
          cd packages/modules/web_themes/koala/source
          npm install
          npm run build --if-present

      - name: Commit and Push Changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add packages/modules/web_themes/koala/web
          git commit -m "Build Web Theme: Koala"
          git push
