name: Python application

on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.2"
      - name: Install dependencies
        run: |
          pip3 install -r "/home/runner/work/core/core/requirements.txt"
      - name: Flake8 with annotations in packages folder
        uses: TrueBrain/actions-flake8@v2.1
        with:
          path: packages
          flake8_version: 5.0.4
      - name: Flake8 with annotations in runs folder
        uses: TrueBrain/actions-flake8@v2.1
        with:
          path: runs
          flake8_version: 5.0.4
      - name: Test with pytest
        run: |
          PYTHONPATH=packages python -m pytest packages --log-cli-level=DEBUG
          PYTHONPATH=runs python -m pytest packages --log-cli-level=DEBUG
