name: Publish docs to Wiki
# based on https://nimblehq.co/blog/create-github-wiki-pull-request
# Trigger this action only if there are changes pushed to the docs/** directory under the main branch
on:
  push:
    paths:
      - docs/** # This includes all sub folders
    branches:
      - master # This can be changed to any branch of your preference

env:
  WIKI_TOKEN: ${{ secrets.WIKI_ACTION_TOKEN }} # Personal Access Token with repo scope
  USER_NAME: "GitHub Actions" # Enter the username of your (bot) account  
  USER_EMAIL: "actions@github.com" # Enter the e-mail of your (bot) account
  OWNER: ${{ github.event.repository.owner.name }} # This is the repository owner
  REPOSITORY_NAME: ${{ github.event.repository.name }} # This is the repository name

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Create folder named `tmp_wiki`
      # 2. Initialize Git
      # 3. Pull old Wiki content
      - name: Pull content from wiki
        run: |
          mkdir tmp_wiki
          cd tmp_wiki
          git init
          git pull https://$WIKI_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git
      # 4. Synchronize differences between `docs` & `tmp_wiki`
      # 5. Push new Wiki content
      - name: Push content to wiki
        run: |
          rsync -av --delete docs/ tmp_wiki/ --exclude .git
          cd tmp_wiki
          git config user.name "$USER_NAME"
          git config user.email "$USER_EMAIL"
          git add .
          git commit -m "Update Wiki content" || echo "No changes to commit"
          git push -f --set-upstream https://$WIKI_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git master
